fast_dev_run = false
random_seed = 42
regenerate = false
tune = true
refit = false
evaluate = false
plot = false
verbose = false
train_size = 0.8
n_trials = 128
method = "rnn"

[filepaths]
data = "data/"
features = "features/"
labels = "labels/factor_scores.csv"
checkpoints = "checkpoints_inter"
logs = "lightning_logs"
train = "analytic/train.csv"
val = "analytic/val.csv"
test = "analytic/test.csv"

[training]
batch_size = 1024
max_epochs = 100
gradient_clip = 1.0

[optimizer]
momentum = 0.99
nesterov = true
[optimizer.lr]
low = 1e-4
high = 1e-2
log = true
[optimizer.weight_decay]
low = 1e-8
high = 1e-1
log = true

[model]
hidden_dim = [16, 32, 64, 128]
[model.dropout]
low = 0.0
high = 0.8
[model.num_layers]
low = 1
high = 5

[logging]
checkpoint_every_n_steps = 1
log_every_n_steps = 1
