random_seed = 42
device = "cuda"
fast_dev_run = false
regenerate = false
tune = true
log = false
predict = false
evaluate = false
importance = true
plot = false
tables = false
verbose = false

[index]
join_on = ["src_subject_id", "eventname"]
sample_id = "src_subject_id"
event = "eventname"
label = "y_{t+1}"
previous_label = "y_t"
split = "split"
site = "site_id_l"
propensity = "acs_raked_propensity_score"

[experiment]
factor_model = "within_event"
factor_models = ["within_event"] # , "across_event", "ksads"]
analyses = [
    # "propensity",
    # "site",
    # "mri",
    "questions",
    # "questions_mri_all",
    # "questions_mri",
    # "questions_symptoms",
    # "symptoms",
    # "questions_mri_symptoms",
    # "autoregressive",
]
analysis = "questions"
split_on = "src_subject_id" # sample_id, site_id

[preprocess]
null_cutoff = 0.25 # 279
columns_to_drop = [
    "_nm",
    "_nt",
    "_na",
    "_language",
    "_answered",
    "ss_sbd",
    "ss_da",
    "_total",
    "_mean",
    "sds_",
    "srpf_",
    "ss_fc",
    "stq_y_ss_week",
    "fes_p_ss_",
]
[preprocess.splits]
train = 0.8
val = 0.1
test = 0.1

[dataloader]
batch_size = 256
num_workers = 10
pin_memory = true
persistent_workers = true
multiprocessing_context = "fork"

[tuner]
n_trials = 128

[trainer]
gradient_clip_val = 1.0
max_epochs = 100
enable_progress_bar = true
enable_model_summary = true

[optimizer]
nesterov = true
momentum = 0.9
lr = 1e-3
weight_decay = 1e-4

[model]
method = "lstm"
hidden_dim = 128
dropout = 0.5
l1_lambda = 1e-5
num_layers = 2
output_dim = 4

[hyperparameters]
[hyperparameters.trainer.max_epochs]
name = "max_epochs"
low = 10
high = 100
[hyperparameters.optimizer.lr]
name = "lr"
low = 1e-4
high = 1e-2
log = true
[hyperparameters.optimizer.weight_decay]
name = "weight_decay"
low = 1e-9
high = 1e-1
log = true
[hyperparameters.optimizer.momentum]
name = "momentum"
low = 0.9
high = 0.99
[hyperparameters.model.method]
name = "method"
low = 0
high = 4
[hyperparameters.model.hidden_dim]
name = "hidden_dim"
low = 64
high = 512
[hyperparameters.model.dropout]
name = "dropout"
low = 0.0
high = 0.90
[hyperparameters.model.l1_lambda]
name = "l1_lambda"
low = 1e-7
high = 1e-1
log = true
[hyperparameters.model.num_layers]
name = "num_layers"
low = 1
high = 3

[logging]
checkpoint_every_n_steps = 1
log_every_n_steps = 1

[evaluation]
n_bootstraps = 1000

[filepaths]
tables = "data/tables/"
plots = "data/plots/"
[filepaths.data]
[filepaths.data.raw]
labels = "data/raw/features/mh_p_cbcl.csv"
dataset = "data/raw/dataset.parquet"
metadata = "data/raw/metadata.parquet"
features = "data/raw/features"
mri = "data/raw/imaging"
splits = "data/raw/splits"
[filepaths.data.processed]
labels = "data/processed/labels.parquet"
features = "data/processed/features.parquet"
dataset = "data/processed/dataset.parquet"
metadata = "data/processed/metadata.parquet"
subject_metadata = "data/processed/subject_metadata.parquet"
[filepaths.data.analytic]
path = ""
train = "train.parquet"
val = "val.parquet"
test = "test.parquet"
[filepaths.data.results]
metrics = "metrics/"
checkpoints = "checkpoints/"
best_model = "checkpoints/best.ckpt"
study = "study.pkl"
logs = "lightning_logs/"
predictions = "predictions.parquet"
shap_values = "shap_values.parquet"
group_shap_values = "group_shap_values.parquet"
shap_coef = "shap_coef.parquet"
group_shap_coef = "group_shap_coef.parquet"

[features]
[features.mh_p_cbcl]
name = "Child Behavior Checklist (CBCL)"
respondent = "Parent"
columns = [
    "cbcl_scr_syn_anxdep_t",
    "cbcl_scr_syn_withdep_t",
    "cbcl_scr_syn_somatic_t",
    "cbcl_scr_syn_social_t",
    "cbcl_scr_syn_thought_t",
    "cbcl_scr_syn_attention_t",
    "cbcl_scr_syn_rulebreak_t",
    "cbcl_scr_syn_aggressive_t",
]
[features.abcd_p_demo]
name = "Demographics"
respondent = "Parent"
columns = [
    "demo_sex_v2",
    "race_ethnicity",
    "demo_comb_income_v2",
    "demo_prnt_ed_v2",
    "demo_prtnr_ed_v2",
    "acs_raked_propensity_score",
]
[features.led_l_adi]
name = "Area deprivation"
respondent = "Parent"
columns = [
    "reshist_addr1_adi_perc",
    "reshist_addr2_adi_perc",
    "reshist_addr3_adi_perc",
]
[features.abcd_y_lt]
name = "Demographics"
respondent = "Parent"
columns = ["interview_age", "interview_date", "site_id_l"] # , 
[features.abcd_aces]
name = "Adverse childhood experiences (ACEs)"
respondent = "Parent"                         # TODO check if this is from parent, youth, or both
columns = ["total_core"]
[features.ce_p_fes]
name = "Family conflict"
respondent = "Parent"
columns = []
[features.ce_y_fes]
name = "Family conflict"
respondent = "Youth"
columns = []
[features.ce_p_nsc]
name = "Neighborhood safety"
respondent = "Parent"
columns = []
[features.ce_y_nsc]
name = "Neighborhood safety"
respondent = "Youth"
columns = []
[features.ce_y_pm]
name = "Parental monitoring"
respondent = "Youth"
columns = []
[features.ce_p_psb]
name = "Prosocial behaviors"
respondent = "Parent"
columns = []
[features.ce_y_psb]
name = "Prosocial behaviors"
respondent = "Youth"
columns = []
[features.ce_y_srpf]
name = "School risk and protective factors"
respondent = "Youth"
columns = []
[features.nt_p_stq]
name = "Screentime"
respondent = "Parent"
columns = []
[features.nt_y_st]
name = "Screentime"
respondent = "Youth"
columns = []
[features.ph_p_sds]
name = "Sleep disturbances"
respondent = "Parent"
columns = []
[features.su_p_pr]
name = "Parental rules"
respondent = "Parent"
columns = []
[features.mh_p_fhx]
name = "Family mental health history"
respondent = "Parent"
columns = [
    "famhx_4_p",
    "fam_history_5_yes_no",
    "fam_history_6_yes_no",
    "fam_history_7_yes_no",
    "fam_history_8_yes_no",
    "fam_history_9_yes_no",
    "fam_history_10_yes_no",
    "fam_history_11_yes_no",
]
[features.mri_y_dti_fa_fs_at]
name = "Diffusion tensor imaging"
respondent = "Youth"
columns = [
    "dmdtifp1_10",
    "dmdtifp1_9",
    "dmdtifp1_19",
    "dmdtifp1_4",
    "dmdtifp1_3",
    "dmdtifp1_6",
    "dmdtifp1_5",
    "dmdtifp1_8",
    "dmdtifp1_7",
    "dmdtifp1_17",
    "dmdtifp1_18",
    "dmdtifp1_1",
    "dmdtifp1_14",
    "dmdtifp1_13",
    "dmdtifp1_27",
    "dmdtifp1_26",
    "dmdtifp1_12",
    "dmdtifp1_11",
    "dmdtifp1_2",
    "dmdtifp1_21",
    "dmdtifp1_20",
]
[features.mri_y_rsfmr_cor_gp_gp]
name = "Resting functional MRI"
respondent = "Youth"
columns = [
    "rsfmri_c_ngd_cgc_ngd_dt",
    "rsfmri_c_ngd_dt_ngd_fo",
    "rsfmri_c_ngd_dt_ngd_dt",
    "rsfmri_c_ngd_fo_ngd_cgc",
    "rsfmri_c_ngd_fo_ngd_fo",
    "rsfmri_c_ngd_cgc_ngd_cgc",
]
[features.mri_y_tfmr_sst_csvcg_dsk]
name = "Task-based functional MRI"
respondent = "Youth"
columns = ["tfmri_sacsvcg_bcdk_bktslh", "tfmri_sacsvcg_bcdk_bktsrh"]
[features.mri_y_tfmr_mid_alrvn_dsk]
name = "Task-based functional MRI"
respondent = "Youth"
columns = ["tfmri_ma_alrvn_b_cds_bkslh", "tfmri_ma_alrvn_b_cds_bksrh"]
[features.mri_y_tfmr_nback_2b_dsk]
name = "Task-based functional MRI"
respondent = "Youth"
columns = ["tfmri_nback_all_339", "tfmri_nback_all_373"]
