fast_dev_run = false
random_seed = 42
tune = true
refit = false
evaluate = true
regenerate = false
verbose = false
train_size = 0.8
n_trials = 64
method = "rnn"

[filepaths]
data = "data/"
features = "features/"
labels = "labels/factor_scores.csv"
checkpoints = "checkpoints"
logs = "lightning_logs"
train = "analytic/train.csv"
val = "analytic/val.csv"
test = "analytic/test.csv"

[training]
batch_size = 512
max_epochs = 50
gradient_clip = 1.0

[optimizer]
momentum = 0.9
nesterov = true
[optimizer.lr]
low = 1e-5
high = 1e-3
log = true
[optimizer.weight_decay]
low = 1e-8
high = 1e-1
log = true

[model]
hidden_dim = [32, 64, 128, 256]
[model.dropout]
low = 0.0
high = 0.5
[model.num_layers]
low = 1
high = 2

[logging]
checkpoint_every_n_steps = 1
log_every_n_steps = 1
